[package]
name = "tm-scaffold"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
hcl-rs = "0.18"
sha2 = "0.10"

[dev-dependencies]
tempfile = "3"
